version: '3'

services:

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASS}@db:5432/${DB_NAME}
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
