# Generated by Django 5.0.1 on 2025-02-24 05:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Relatório %d/%m/%Y', max_length=256)),
                ('date_creation', models.DateTimeField(default=datetime.datetime(2025, 2, 24, 2, 2, 21, 865146))),
            ],
        ),
        migrations.CreateModel(
            name='Report_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField(blank=True, default=None, null=True)),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
            ],
        ),
    ]
