# Generated by Django 4.2.5 on 2023-12-17 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 0, 23, 23, 894291)),
        ),
    ]
