# Generated by Django 5.0.1 on 2025-02-24 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 2, 4, 44, 430729)),
        ),
    ]
