<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-08-13 13:31
=======
# Generated by Django 5.0.1 on 2024-08-13 20:01
>>>>>>> 17f58d65a42d19fff88981f09510f3901f18314f

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_report_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_creation',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 10, 31, 7, 49318)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 17, 1, 20, 808321)),
>>>>>>> 17f58d65a42d19fff88981f09510f3901f18314f
        ),
    ]
