# Generated by Django 5.0.1 on 2024-09-25 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_alter_report_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 18, 20, 7, 220614)),
        ),
    ]
