# Generated by Django 5.1.1 on 2024-09-13 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_report_police_alter_report_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='police',
        ),
        migrations.AlterField(
            model_name='report',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 16, 33, 23, 718910)),
        ),
    ]
