<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-09-25 21:21
=======
# Generated by Django 5.0.1 on 2024-09-13 19:12
>>>>>>> 056393495dc202fa22526f8c87495687c65c7768

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_alter_report_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_creation',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 18, 21, 14, 902993)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 16, 12, 39, 529508)),
>>>>>>> 056393495dc202fa22526f8c87495687c65c7768
        ),
    ]
