# Generated by Django 4.2.5 on 2023-10-06 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False, verbose_name='Ativado')),
                ('amount', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('image_path', models.FileField(upload_to='Modelos/municoes/')),
                ('caliber', models.CharField(choices=[('', 'SELECIONE'), ('9mm', '9mm'), ('.45 ACP', '.45 ACP'), ('.380 ACP', '.380 ACP'), ('.40 S&W', '.40 S&W'), ('.357 Magnum', '.357 Magnum'), ('.44 Magnum', '.44 Magnum'), ('5.56mm', '5.56mm'), ('7.62mm', '7.62mm'), ('.22 LR', '.22 LR')], default='SELECIONE', max_length=30, verbose_name='Calibre')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Model_accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False, verbose_name='Ativado')),
                ('model', models.TextField(verbose_name='Modelo do armamento')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image_path', models.FileField(upload_to='Modelos/acessorios/')),
            ],
        ),
        migrations.CreateModel(
            name='Model_armament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False, verbose_name='Ativado')),
                ('model', models.TextField(verbose_name='Modelo do armamento')),
                ('caliber', models.CharField(choices=[('', 'SELECIONE'), ('9mm', '9mm'), ('.45 ACP', '.45 ACP'), ('.380 ACP', '.380 ACP'), ('.40 S&W', '.40 S&W'), ('.357 Magnum', '.357 Magnum'), ('.44 Magnum', '.44 Magnum'), ('5.56mm', '5.56mm'), ('7.62mm', '7.62mm'), ('.22 LR', '.22 LR')], default='SELECIONE', max_length=30, verbose_name='Calibre')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image_path', models.FileField(upload_to='Modelos/armamentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Model_grenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False, verbose_name='Ativado')),
                ('model', models.TextField(verbose_name='Modelo do armamento')),
                ('image_path', models.FileField(upload_to='Modelos/granadas/')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Model_wearable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False, verbose_name='Ativado')),
                ('model', models.TextField(verbose_name='Modelo do armamento')),
                ('size', models.CharField(max_length=10, verbose_name='Tamanho')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image_path', models.FileField(upload_to='Modelos/vestiveis/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('date_register', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de registro')),
                ('activated', models.BooleanField(default=False, verbose_name='Ativado')),
                ('serial_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='Numero de série')),
                ('uid', models.CharField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='uid')),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('6H', '6H'), ('8H', '8H'), ('12H', '12H'), ('24H', '24H'), ('CONSERTO', 'CONSERTO'), ('INDETERMINADO', 'INDETERMINADO'), ('REQUISIÇÃO JUDICIAL', 'REQUISIÇÃO JUDICIAL')], default='Disponível', max_length=20, verbose_name='Estado atual')),
                ('model_id', models.PositiveIntegerField(verbose_name='modelo')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo do modelo')),
            ],
            options={
                'verbose_name': 'Equipamento',
            },
        ),
    ]
