# Generated by Django 4.2.5 on 2023-12-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_bullet_activator_equipment_activator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='uid',
            field=models.CharField(default=None, max_length=200, primary_key=True, serialize=False, verbose_name='uid'),
        ),
    ]
