# Generated by Django 4.2.5 on 2023-12-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Numero de série'),
        ),
    ]
