# Generated by Django 5.0 on 2024-01-09 18:08

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipment_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='activated',
            field=models.IntegerField(default=0, verbose_name='Ativado'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='caliber',
            field=models.CharField(choices=[('', 'SELECIONE'), ('9mm', '9mm'), ('.45 ACP', '.45 ACP'), ('.380 ACP', '.380 ACP'), ('.40 S&W', '.40 S&W'), ('.357 Magnum', '.357 Magnum'), ('.44 Magnum', '.44 Magnum'), ('5.56mm', '5.56mm'), ('7.62mm', '7.62mm'), ('.22 LR', '.22 LR')], default='SELECIONE', max_length=30, unique=True, verbose_name='Calibre'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='activated',
            field=models.IntegerField(default=0, verbose_name='Ativado'),
        ),
        migrations.AlterField(
            model_name='model_accessory',
            name='activated',
            field=models.IntegerField(default=0, verbose_name='Ativado'),
        ),
        migrations.AlterField(
            model_name='model_armament',
            name='activated',
            field=models.IntegerField(default=0, verbose_name='Ativado'),
        ),
        migrations.AlterField(
            model_name='model_grenada',
            name='activated',
            field=models.IntegerField(default=0, verbose_name='Ativado'),
        ),
        migrations.AlterField(
            model_name='model_wearable',
            name='activated',
            field=models.IntegerField(default=0, verbose_name='Ativado'),
        ),
    ]
