# Generated by Django 4.1.3 on 2024-01-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_bullet_activated_alter_bullet_caliber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='caliber',
            field=models.CharField(choices=[['', 'SELECIONE'], ['9mm', '9mm'], ['.45 ACP', '.45 ACP'], ['.380 ACP', '.380 ACP'], ['.40 S&W', '.40 S&W'], ['.357 Magnum', '.357 Magnum'], ['.44 Magnum', '.44 Magnum'], ['5.56mm', '5.56mm'], ['7.62mm', '7.62mm'], ['.22 LR', '.22 LR']], default='SELECIONE', max_length=30, unique=True, verbose_name='Calibre'),
        ),
        migrations.AlterField(
            model_name='model_armament',
            name='caliber',
            field=models.CharField(choices=[['', 'SELECIONE'], ['9mm', '9mm'], ['.45 ACP', '.45 ACP'], ['.380 ACP', '.380 ACP'], ['.40 S&W', '.40 S&W'], ['.357 Magnum', '.357 Magnum'], ['.44 Magnum', '.44 Magnum'], ['5.56mm', '5.56mm'], ['7.62mm', '7.62mm'], ['.22 LR', '.22 LR']], default='SELECIONE', max_length=30, verbose_name='Calibre'),
        ),
    ]
