# Generated by Django 5.0.1 on 2024-08-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_bullet_caliber_alter_model_armament_caliber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_accessory',
            name='model',
            field=models.TextField(verbose_name='Modelo do acessório'),
        ),
        migrations.AlterField(
            model_name='model_grenada',
            name='model',
            field=models.TextField(verbose_name='Modelo da granada'),
        ),
        migrations.AlterField(
            model_name='model_wearable',
            name='model',
            field=models.TextField(verbose_name='Modelo do vestimento'),
        ),
    ]
