# Generated by Django 4.2.5 on 2023-10-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='name',
            field=models.CharField(default='Ediel', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
