# Generated by Django 5.0.1 on 2024-10-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
