# Generated by Django 4.2.5 on 2023-12-08 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_alter_police_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='activator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
