# Generated by Django 4.2.5 on 2023-12-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0006_police_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='posto',
            field=models.CharField(choices=[('Soldado', 'Soldado'), ('Cabo', 'Cabo'), ('Primeiro Sargento', 'Primeiro Sargento'), ('Subtenente', 'Subtenente'), ('Aspirante', 'Aspirante'), ('Primeiro Tenente', 'Primeiro Tenente'), ('Capitão', 'Capitão'), ('Major', 'Major'), ('Tenente Coronel', 'Tenente Coronel'), ('Coronel', 'Coronel'), ('Comandante Geral', 'Comandante Geral')], max_length=50),
        ),
    ]
