# Generated by Django 5.0 on 2024-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0007_alter_police_posto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='activated',
            field=models.IntegerField(default=0, verbose_name='Ativado'),
        ),
        migrations.AlterField(
            model_name='police',
            name='posto',
            field=models.CharField(choices=[('Soldado', 'Soldado'), ('Cabo', 'Cabo'), ('Primeiro Sargento', 'Primeiro Sargento'), ('Subtenente', 'Subtenente'), ('Aspirante', 'Aspirante'), ('Primeiro Tenente', 'Primeiro Tenente'), ('Capitão', 'Capitão'), ('Major', 'Major'), ('Tenente Coronel', 'Tenente Coronel'), ('Coronel', 'Coronel'), ('Comandante Geral', 'Comandante Geral')], max_length=50, verbose_name='Posto/Graduação'),
        ),
        migrations.AlterField(
            model_name='police',
            name='tipo',
            field=models.CharField(choices=[('Policial', 'Policial'), ('Adjunto', 'Adjunto'), ('Administrador', 'Administrador')], default='Policial', max_length=20),
        ),
    ]
