# Generated by Django 5.0.1 on 2024-01-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0008_alter_police_activated_alter_police_posto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='posto',
            field=models.CharField(choices=[('Soldado', 'Soldado'), ('Cabo', 'Cabo'), ('Primeiro Sargento', 'Primeiro Sargento'), ('Subtenente', 'Subtenente'), ('Aspirante', 'Aspirante'), ('Primeiro Tenente', 'Primeiro Tenente'), ('CapitÃ£o', 'CapitÃ£o'), ('Major', 'Major'), ('Tenente Coronel', 'Tenente Coronel'), ('Coronel', 'Coronel'), ('Comandante Geral', 'Comandante Geral')], max_length=50, verbose_name='Posto/Graduação'),
        ),
    ]
