# Generated by Django 5.0.1 on 2024-08-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0010_alter_police_posto'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='pushToken',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
