# Generated by Django 5.0.1 on 2024-09-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0011_police_pushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='posto',
            field=models.CharField(choices=[('Soldado', 'Soldado'), ('Cabo', 'Cabo'), ('Primeiro Sargento', 'Primeiro Sargento'), ('Subtenente', 'Subtenente'), ('Aspirante', 'Aspirante'), ('Primeiro Tenente', 'Primeiro Tenente'), ('Capitão', 'Capitão'), ('Major', 'Major'), ('Tenente Coronel', 'Tenente Coronel'), ('Coronel', 'Coronel'), ('Comandante Geral', 'Comandante Geral')], max_length=50, verbose_name='Posto/Graduação'),
        ),
    ]
