# Generated by Django 5.0.1 on 2024-10-10 14:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_load', models.DateTimeField(default=datetime.datetime(2024, 10, 10, 11, 42, 37, 759777))),
                ('expected_load_return_date', models.DateTimeField(null=True, verbose_name='Data Prevista de Devolução')),
                ('returned_load_date', models.DateTimeField(null=True, verbose_name='Data de Descarregamento')),
                ('turn_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Devolvido', 'Devolvido'), ('Pendente', 'Pendente'), ('Parcialmente devolvido', 'Parcialmente devolvido'), ('Justificado', 'Justificado')], default='DENTRO DO PRAZO', max_length=50, verbose_name='horário_carga')),
                ('adjunct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='adjunto', to=settings.AUTH_USER_MODEL)),
                ('load_unload', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='load.load')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default='1', null=True, verbose_name='Quantidade')),
                ('observation', models.TextField(default=None, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('Devolvido', 'Devolvido'), ('Pendente', 'Pendente'), ('Justificado', 'Justificado')], default='Pendente', max_length=20, verbose_name='Status')),
                ('bullet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.bullet')),
                ('equipment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_loads', to='load.load')),
            ],
        ),
    ]
