# Generated by Django 5.0.1 on 2025-02-24 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0002_alter_load_date_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='date_load',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 2, 4, 34, 879019)),
        ),
    ]
