# Generated by Django 4.2.5 on 2023-12-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0002_load_load_unload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_load',
            name='status',
            field=models.CharField(choices=[('Devolvido', 'Devolvido'), ('Pendente', 'Pendente'), ('Justificado', 'Justificado')], default='Pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('Devolvido', 'Devolvido'), ('Pendente', 'Pendente'), ('Parcialmente devolvido', 'Parcialmente devolvido'), ('Justificado', 'Justificado')], default='DENTRO DO PRAZO', max_length=50, verbose_name='horário_carga'),
        ),
    ]
