<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-09-25 21:20
=======
<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-09-13 19:12
=======
# Generated by Django 5.0.1 on 2024-09-13 14:49
>>>>>>> main
>>>>>>> 056393495dc202fa22526f8c87495687c65c7768

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0003_alter_equipment_load_status_alter_load_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='date_load',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 18, 20, 7, 221637)),
=======
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 16, 12, 19, 851425)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 11, 49, 12, 930622)),
>>>>>>> main
>>>>>>> 056393495dc202fa22526f8c87495687c65c7768
        ),
    ]
