# Generated by Django 5.0.1 on 2024-09-13 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0003_alter_equipment_load_status_alter_load_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='date_load',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 11, 49, 12, 930622)),
        ),
    ]
