<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-09-13 19:12
=======
# Generated by Django 5.1.1 on 2024-09-13 19:31
>>>>>>> alteracoes

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0004_alter_load_date_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='date_load',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 16, 12, 27, 704731)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 16, 31, 43, 579925)),
>>>>>>> alteracoes
        ),
    ]
