<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-09-13 19:12
=======
# Generated by Django 5.1.1 on 2024-09-13 19:33
>>>>>>> alteracoes

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0005_alter_load_date_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='date_load',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 16, 12, 34, 460825)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 16, 33, 23, 719910)),
>>>>>>> alteracoes
        ),
    ]
