# Generated by Django 5.0.1 on 2024-09-25 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0006_alter_load_date_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='date_load',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 18, 21, 4, 614070)),
        ),
    ]
