# Generated by Django 5.0.1 on 2024-09-13 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0007_alter_load_date_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='date_load',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 16, 12, 45, 993152)),
        ),
    ]
